### ISSUE TITLE
rpn source file missing?

### ISSUE THREAD

**Issue by wisemoth** [voidware/reckon#2]
I've been trying to build the code for the 9860 to rectify the GII key-mapping issue (issue #1).  I've fixed up a few things, but the one that I think is a problem is that there's no definition (as far as I can see) of `_do_rpn()`.  The `Reckon.dlr` file hints at a `rpn.cpp` source file, as does the project file. 

Can it be committed?

**Comment by voidware** [comment]
sorry yes, the file rpn.cpp was missing.

i have added it.

-- hugh.

**Comment by wisemoth** [comment]
Thanks!
