### ISSUE TITLE
x^n or exp(x) = crash

### ISSUE THREAD

**Issue by watchmakerful** [voidware/reckon#4]
Every time I try to use, plot or plot3d anything containing powers or exponentials my calculator immediately reboots. All other functions are calculated fine (e.g. log or trigonometric functions).
Fx9750GII (SH4) flashed with a Graph75+E v2.05 image.

**Comment by watchmakerful** [comment]
Confirmed in SDK! 
`Execution has stopped due to an error!
Nonexisting memory by data write access at 87FF:FFFC`
![887](https://user-images.githubusercontent.com/10285128/41438806-365d75d4-7031-11e8-94a0-615cedfd424e.jpg)

**Comment by voidware** [comment]
Looks like something else is broken. I'll take a look into it.

-- hugh.

**Comment by voidware** [comment]
Fixed.

Powering didn't work. eg 2.1^2 would crash. It appears this was a 
problem with the casio compiler, the overloading of "pow(x,a)" for a 
integer, instead called pow(x,BCD(a)) which called itself again! This 
only happen on the casio compiler, even after making "explicit BCD(int4)".

Workaround was to change function name to "powInt" to force it to use 
correct function.

-- hugh.

**Comment by watchmakerful** [comment]
I'll try it...

**Comment by watchmakerful** [comment]
Fixed.
