### ISSUE TITLE
Division by zero is broken!

### ISSUE THREAD

**Issue by watchmakerful** [voidware/reckon#7]
Enter 2/0, the app says 0. 
![889](https://user-images.githubusercontent.com/10285128/41492886-b0b1123a-710a-11e8-80c1-66cb77076d5a.jpg)
Enter 1/0.000.
![890](https://user-images.githubusercontent.com/10285128/41492907-f1bd1a94-710a-11e8-9d86-a6d87cdefeee.jpg)

**Comment by voidware** [comment]
Fixed.
